name: Process-PSModule

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  Process-PSModule:
    uses: PSModule/Actions/.github/workflows/workflow.yml@main
    secrets: inherit
